Nerds
kabollinger03/sProject pull request #41
Opened 2019-03-29 16:50 UTC by kjones2296

This is Nerds' login page and email java files

2019-03-29 18:20 UTC, jmonson2 requested changes
index.html has password entered as plain text. Should be type password.

2019-03-29 18:35 UTC, kabollinger03 reviewed
Mostly just some minor issues

2019-03-29 18:35 UTC, kabollinger03 commented on Emails/src/SendEmail.java
> +    	String[] arr = new String[]{"phillipphoong@gmail.com", "hunter.pierce2@knights.ucf.edu", "icebergkj@yahoo.com"};
This looks like testing data. Does that need to be in master?

2019-03-29 18:35 UTC, kabollinger03 commented on Emails/src/SendEmail.java
> +        String to=email;
why bother with variable assignment when you aren't doing any processing?

2019-03-29 18:35 UTC, kabollinger03 commented on Login/index.html
> +					  <input type="text" class="form-control-lg form-control" placeholder="Email" aria-label="Email" aria-describedby="basic-addon1">
type=text but it is an email. I know the HTML email validation is dumb and you are making a JS validation anyway, but....

2019-03-29 18:35 UTC, kabollinger03 commented on Login/index.html
> +					  <input type="text" class="form-control-lg form-control" placeholder="Email" aria-label="Email" aria-describedby="basic-addon1">
See previous comment about email

2019-03-29 18:35 UTC, kabollinger03 commented on Login/js/form.js
> +}
No other validation at this point? Not block worthy cause we are not dealing with web at this point but worth mentioning

2019-03-29 18:35 UTC, kabollinger03 submitted a review, later dismissed

2019-03-29 18:35 UTC, kabollinger03 commented on Login/index.html
> +					  <input type="text" class="form-control-lg form-control" placeholder="Password" aria-label="Password" aria-describedby="basic-addon2">
password needs to be redacted! type=password

2019-03-29 20:12 UTC, jmonson2 requested changes

2019-03-29 20:12 UTC, jmonson2 commented on Login/index.html
> +					  <input type="text" class="form-control-lg form-control" placeholder="Password" aria-label="Password" aria-describedby="basic-addon2">
Password needs to be type="password"

2019-03-30 23:04 UTC, kabollinger03 commented
Going through ZenHub... best practice is to make one PR per task. Or at least make everything in a PR relate to one story. It is ok but now IDK what story to put this PR with.

2019-04-01 17:29 UTC, phoongp approved these changes
Great work!

2019-04-02 19:10 UTC, SeleneShen approved these changes
good job

2019-04-02 19:31 UTC, closed without merging