basic create class page for instructors.
kabollinger03/sProject pull request #8
Opened 2019-03-25 22:40 UTC by apj11c

Place holders for data, etc...

2019-03-26 17:05 UTC, kabollinger03 commented on createClass.html
> +		<input type="file" id="xcelfile" accept=".xcel" required title=".xcel">
Uuumm..... that is not a valid file extension. You want `.xlsx` and maybe `.xls`. See https://en.wikipedia.org/wiki/List_of_Microsoft_Office_filename_extensions

2019-03-26 17:08 UTC, kabollinger03 requested changes

2019-03-26 17:08 UTC, kabollinger03 commented on createClass.html
> +		<input type="file" id="xcelfile" accept=".xcel" required title=".xcel">
Uuumm..... `.xcel` is not a valid file extension. You want `.xlsx` and maybe `.xls`. See https://en.wikipedia.org/wiki/List_of_Microsoft_Office_filename_extensions

2019-03-26 17:20 UTC, kabollinger03 commented
The page title is `Create Class` but the heading is `Create Course`. That should be consistent. Should most likely be class because in the project vernacular "class" = "a group of students participating in a stream" and "course" = "a specific part of a module". Instructors do not have the "edit courses" permission.

While I'm at it, this page is also for editing information right? So shouldn't the title reflect that? IDK, maybe `create or edit class`?

2019-03-27 17:06 UTC, kabollinger03 approved these changes

2019-03-29 16:30 UTC, ChrisSMendoza approved these changes

2019-03-29 16:31 UTC, closed without merging

2019-03-29 16:34 UTC, ChrisSMendoza commented
Changes weren't being reflected in this pull request.